-- Create tables
CREATE TABLE orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL,
    share_id INTEGER NOT NULL,
    shares INTEGER NOT NULL,
    by_price REAL NOT NULL,
    date_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE shares (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    symbol CHAR(8) NOT NULL UNIQUE
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    hash TEXT VARCHAR(255) NOT NULL,
    cash REAL NOT NULL DEFAULT 10000.00
);

-- Delete tables(for clear all data)
DROP TABLE orders;
DROP TABLE shares;
DROP TABLE users;